### ISSUE TITLE
Сбой при освобождении ресурсов в ядре

### ISSUE THREAD

**Issue by tima2015** [tima2015/Color-it#14]
```
FATAL EXCEPTION: GLThread 1047
Process: com.forward.colorit, PID: 18320
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.forward.colorit.ui.MenuScreen.dispose()' on a null object reference
	at com.forward.colorit.Core.dispose(Core.java:153)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:494)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1571)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)
```

Большую информацию можете просмотреть в play console

**Comment by tima2015** [comment]
Исключение выскакивало при освобождении памяти, в случае если приложение закрывал ось не дожидаясь окончания загрузки. Некоторые поля инициализируются только после её оканчания. Следовательно при освобождении не инициализированого поля и выскакивало исключение. Исправлено в последнем комите
